### Type definitions saved at 2020-05-17T19:11:39.907Z ###

type MarkdownRemarkFrontmatter {
  title: String
  templateKey: String
  description: String
  image: File @fileByRelativePath
  images: [MarkdownRemarkFrontmatterImages]
  location: String
  name: String
  eventbrite: String
  url: String
  links: [MarkdownRemarkFrontmatterLinks]
  status: String
  date: Date @dateformat
  datetime: Date @dateformat
  early_bird: Date @dateformat
  active: Boolean
  stages: [MarkdownRemarkFrontmatterStages]
  tickets: [MarkdownRemarkFrontmatterTickets]
  timetable: File @fileByRelativePath
  category: String
  order: Int
  events: [MarkdownRemark] @link(by: "frontmatter.title")
  event: MarkdownRemark @link(by: "frontmatter.title")
}

type MarkdownRemarkFrontmatterImages {
  alt: String
  image: File @fileByRelativePath
}

type MarkdownRemarkFrontmatterLinks {
  name: String
  url: String
}

type MarkdownRemarkFrontmatterStages {
  name: String
  acts: [MarkdownRemarkFrontmatterStagesActs]
}

type MarkdownRemarkFrontmatterStagesActs {
  artist: MarkdownRemark @link(by: "frontmatter.title")
  announced: Boolean
}

type MarkdownRemarkFrontmatterTickets {
  title: String
  price: Float
  price_early: Float
  url: String
  body: String
}

type MarkdownRemarkFields {
  slug: String
}